name: feed_delivery
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.3
  go_router_paths: ^0.2.2
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^4.2.1
  flutter_multi_formatter: ^2.13.0
  intl_utils: ^2.8.7
  mask_text_input_formatter: ^2.9.0
  flutter_barcode_scanner: ^2.0.0

  json_annotation: ^4.9.0
  overlay_support: ^2.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: 2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  analyzer: ^6.2.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
